name: Upload Python Package

on:
  push:
    branches:
      - main
#  release:
#    types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IS_MATCHED: 0
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.7

      - name: Check folder
        id: check-folder
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo $file
            if [[ $file =~ '^_ext/python' ]]; then
              echo "${file} matched"
              export IS_MATCHED=1
              break
            fi
          done

      - name: Set up Python
        if: ${{ env.IS_MATCHED == '1' }}
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Install dependencies
        if: ${{ env.IS_MATCHED == '1' }}
        run: |
          cd python
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install -r requirements.txt

      - name: Build and publish
        if: ${{ env.IS_MATCHED == '1' }}
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          cd python
          python setup.py sdist bdist_wheel
          pip install twine
#          twine upload dist/*
